import { useState } from 'react';
import { Shell, Stat } from './shared';
import { contrast } from './domain';
export default function App() { const [fg, setFg] = useState('#ffffff'); const [bg, setBg] = useState('#16324f'); const [tab, setTab] = useState(0); const [open, setOpen] = useState(false); const [notice, setNotice] = useState(''); const ratio = contrast(fg, bg); const tabs = ['Contraste', 'Componentes', 'Tokens']; return <Shell name="A11y Lab" title="Interfaces para todas as pessoas." description="Explore contraste, estados e padrões de interação. Uma bancada de design que coloca acessibilidade no centro." accent="#ffc784"><div className="row" role="tablist" aria-label="Ferramentas do laboratório" style={{ marginBottom: 24 }}>{tabs.map((t, i) => <button key={t} id={'tab-' + i} role="tab" aria-selected={tab === i} aria-controls={'panel-' + i} tabIndex={tab === i ? 0 : -1} onClick={() => setTab(i)} onKeyDown={e => { const next = e.key === 'ArrowRight' ? (i + 1) % 3 : e.key === 'ArrowLeft' ? (i + 2) % 3 : e.key === 'Home' ? 0 : e.key === 'End' ? 2 : null; if (next !== null) {
    e.preventDefault();
    setTab(next);
    document.getElementById('tab-' + next)?.focus();
} }}>{t}</button>)}</div><section className="panel" role="tabpanel" id={'panel-' + tab} aria-labelledby={'tab-' + tab} tabIndex={0}>{tab === 0 ? <><h2>Verificador de contraste</h2><div className="form"><label>Cor do texto<input type="color" value={fg} onChange={e => setFg(e.target.value)}/></label><label>Cor do fundo<input type="color" value={bg} onChange={e => setBg(e.target.value)}/></label></div><div style={{ background: bg, color: fg, padding: 32, borderRadius: 12, margin: '24px 0' }}><h2 style={{ color: fg }}>Design legível é design melhor.</h2><span>Texto de exemplo para visualizar a combinação selecionada.</span></div><div className="grid"><Stat label="Relação de contraste" value={ratio.toFixed(2) + ':1'}/><Stat label="AA • texto normal" value={ratio >= 4.5 ? 'Aprovado' : 'Reprovado'}/><Stat label="AAA • texto normal" value={ratio >= 7 ? 'Aprovado' : 'Reprovado'}/></div><p>A análise avalia apenas o contraste das duas cores opacas escolhidas; não é uma auditoria completa da página.</p></> : tab === 1 ? <><h2>Estados e interação</h2><div className="row"><button className="primary" onClick={() => setNotice('Ação concluída com sucesso.')}>Confirmar ação</button><button disabled>Indisponível</button></div><p aria-live="polite">{notice}</p><button aria-expanded={open} aria-controls="details" onClick={() => setOpen(!open)}>Como testar com teclado {open ? '−' : '+'}</button><div id="details" hidden={!open}><p>Use Tab para navegar, Enter ou Espaço para ativar botões e as setas para trocar as abas. O foco deve permanecer visível.</p></div><label style={{ marginTop: 24 }}>Campo obrigatório<input required placeholder="Seu nome" aria-describedby="name-help"/></label><p id="name-help">Exemplo de campo associado a uma descrição.</p></> : <><h2>Tokens exportáveis</h2><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify({ 'color.text': fg, 'color.surface': bg, 'radius.card': '18px', 'space.base': '8px' }, null, 2)}</pre><button onClick={async () => { try {
    await navigator.clipboard.writeText(JSON.stringify({ text: fg, surface: bg, radius: '18px' }, null, 2));
    setNotice('Tokens copiados.');
}
catch {
    setNotice('Não foi possível copiar. Selecione o texto acima.');
} }}>Copiar tokens</button><p aria-live="polite">{notice}</p></>}</section></Shell>; }
